// swift-tools-version: 5.10
import PackageDescription

// NOTE: This Package.swift exists purely as a fast local compile/test harness
// (`swift build` / `swift test`) during development on machines that only have
// the Command Line Tools installed (no full Xcode / xcodebuild available).
//
// The actual shippable macOS app target (with Info.plist, entitlements,
// MenuBarExtra bundle identity, sandbox, etc.) is generated by XcodeGen from
// `project.yml` into `PersonalSecretary.xcodeproj`. Both point at the same
// `Sources/PersonalSecretary` tree, so there is a single source of truth.
let package = Package(
    name: "PersonalSecretary",
    platforms: [.macOS(.v14)],
    targets: [
        .executableTarget(
            name: "PersonalSecretary",
            path: "Sources/PersonalSecretary"
        ),
        .testTarget(
            name: "PersonalSecretaryTests",
            dependencies: ["PersonalSecretary"],
            path: "Tests/PersonalSecretaryTests"
        )
    ]
)
